version: "3.7"
services:
  postgres:
    build: ./postgreSQL
    ports:
      - 5432:5432
    volumes:
      - data-vol:/var/lib/postgresql/data
      - backup-vol:/backups
    environment: 
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb

volumes:
  data-vol: {}
  backup-vol: {}