version: '3.6'

networks:
  db_net:
    driver: bridge

volumes:
    postgres_6_4_db: {}
    postgres_6_4_backup: {}

services:

  postgres:
    image: postgres:13
    container_name: postgres_6_4
    volumes:
      - postgres_6_4_db:/var/lib/postgresql/data
      - postgres_6_4_backup:/var/lib/postgresql/backup
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - db_net
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - db_net
    ports:
      - 8080:8080